/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#cbceff",
        "surface-variant": "#192540",
        "surface-dim": "#060e20",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#f271b5",
        "on-primary": "#00374d",
        "inverse-primary": "#00668b",
        "primary-fixed-dim": "#05a9e3",
        "primary": "#3bbffa",
        "surface-bright": "#1f2b49",
        "surface-tint": "#3bbffa",
        "outline": "#6d758c",
        "on-secondary-fixed": "#192490",
        "surface-container": "#0f1930",
        "error-container": "#9f0519",
        "error": "#ff716c",
        "on-primary-fixed": "#00121d",
        "on-tertiary-fixed-variant": "#73004b",
        "surface-container-high": "#141f38",
        "primary-container": "#22b1ec",
        "on-primary-container": "#002b3d",
        "secondary-container": "#2f3aa3",
        "surface-container-highest": "#192540",
        "on-tertiary-fixed": "#360021",
        "outline-variant": "#40485d",
        "inverse-on-surface": "#4d556b",
        "tertiary-container": "#f673b7",
        "surface": "#060e20",
        "on-primary-fixed-variant": "#003a50",
        "primary-fixed": "#2db7f2",
        "tertiary-fixed-dim": "#f976ba",
        "background": "#060e20",
        "on-background": "#dee5ff",
        "on-secondary-fixed-variant": "#3a45ad",
        "on-secondary": "#000974",
        "secondary-dim": "#8a95ff",
        "on-surface": "#dee5ff",
        "secondary-fixed-dim": "#babfff",
        "on-tertiary": "#5f003e",
        "primary-dim": "#05a9e3",
        "tertiary-fixed": "#ff8bc5",
        "error-dim": "#d7383b",
        "on-error-container": "#ffa8a3",
        "on-secondary-container": "#c9cdff",
        "on-error": "#490006",
        "on-surface-variant": "#a3aac4",
        "on-tertiary-container": "#4a002f",
        "secondary": "#8a95ff",
        "tertiary": "#ff86c3",
        "inverse-surface": "#faf8ff",
        "surface-container-low": "#091328"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
