/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Modern Dark Cinema design tokens ───────────────────
        'bg-deep':     '#020203',
        'bg-base':     '#050506',
        'bg-elevated': '#0a0a0c',
        'surface':     'rgba(255,255,255,0.05)',
        'surface-hi':  'rgba(255,255,255,0.08)',
        'fg':          '#EDEDEF',
        'fg-muted':    '#8A8F98',
        'fg-subtle':   '#4B5060',
        'accent':      '#5E6AD2',
        'accent-glow': 'rgba(94,106,210,0.2)',
        'accent-hi':   '#7B87E8',
        'border':      'rgba(255,255,255,0.08)',
        'border-hi':   'rgba(255,255,255,0.15)',

        // ── Semantic status ─────────────────────────────────────
        'status-success': '#4ADE80',
        'status-warning': '#FBBF24',
        'status-danger':  '#F87171',
        'status-info':    '#60A5FA',

        // ── Legacy compat (keep existing components working) ────
        'primary':                   '#5E6AD2',
        'secondary':                 '#8B7CF7',
        'background':                '#020203',
        'on-background':             '#EDEDEF',
        'on-surface':                '#EDEDEF',
        'on-surface-variant':        '#8A8F98',
        'surface-container':         '#0a0a0c',
        'surface-container-high':    '#0f1016',
        'surface-container-highest': '#141520',
        'surface-container-low':     '#050506',
        'outline':                   '#4B5060',
        'outline-variant':           'rgba(255,255,255,0.08)',
        'error':                     '#F87171',
        'surface-dim':               '#020203',
        'surface-bright':            '#0f1016',
        'surface-variant':           '#0a0a0c',
        'surface-tint':              '#5E6AD2',
        'on-primary':                '#fff',
        'on-secondary':              '#fff',
        'on-tertiary':               '#fff',
        'tertiary':                  '#F09580',
        'tertiary-dim':              '#F09580',
        'tertiary-fixed':            '#F09580',
        'tertiary-fixed-dim':        '#F09580',
        'on-tertiary-fixed':         '#fff',
        'on-tertiary-fixed-variant': '#fff',
        'on-tertiary-container':     '#fff',
        'tertiary-container':        '#F09580',
        'secondary-dim':             '#8B7CF7',
        'secondary-fixed':           '#8B7CF7',
        'secondary-fixed-dim':       '#8B7CF7',
        'secondary-container':       'rgba(139,124,247,0.15)',
        'on-secondary-fixed':        '#fff',
        'on-secondary-fixed-variant':'#fff',
        'on-secondary-container':    '#8B7CF7',
        'primary-dim':               '#5E6AD2',
        'primary-fixed':             '#5E6AD2',
        'primary-fixed-dim':         '#5E6AD2',
        'primary-container':         'rgba(94,106,210,0.15)',
        'on-primary-fixed':          '#fff',
        'on-primary-fixed-variant':  '#fff',
        'on-primary-container':      '#5E6AD2',
        'inverse-primary':           '#5E6AD2',
        'inverse-surface':           '#EDEDEF',
        'inverse-on-surface':        '#020203',
        'error-container':           'rgba(248,113,113,0.15)',
        'on-error':                  '#fff',
        'on-error-container':        '#F87171',
        'surface-container-lowest':  '#000000',
      },

      fontFamily: {
        sans:     ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['Inter', 'system-ui', 'sans-serif'],
        mono:     ['JetBrains Mono', 'Fira Code', 'monospace'],
      },

      borderRadius: {
        DEFAULT: '10px',
        sm:      '6px',
        md:      '10px',
        lg:      '16px',
        xl:      '20px',
        '2xl':   '24px',
        full:    '9999px',
      },

      boxShadow: {
        pip:      '0 4px 24px rgba(0,0,0,0.5)',
        dropdown: '0 4px 16px rgba(0,0,0,0.4)',
        modal:    '0 16px 48px rgba(0,0,0,0.6)',
        glow:     '0 0 20px rgba(94,106,210,0.3)',
        'glow-sm':'0 0 10px rgba(94,106,210,0.2)',
      },

      transitionTimingFunction: {
        expo: 'cubic-bezier(0.16,1,0.3,1)',
      },

      keyframes: {
        blobDrift: {
          '0%,100%': { transform: 'translate(0,0) scale(1)' },
          '33%':     { transform: 'translate(30px,-20px) scale(1.04)' },
          '66%':     { transform: 'translate(-20px,15px) scale(0.97)' },
        },
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'blob-slow': 'blobDrift 12s ease-in-out infinite',
        'blob-mid':  'blobDrift 16s ease-in-out infinite 4s',
        'fade-up':   'fadeUp 300ms cubic-bezier(0.16,1,0.3,1) both',
        'fade-in':   'fadeIn 200ms ease-out both',
      },
    },
  },
  plugins: [],
}
