/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // --- Landing Page Specific Colors ---
        'landing-secondary-fixed': '#cbceff',
        'landing-surface-variant': '#192540',
        'landing-surface-dim': '#060e20',
        'landing-surface-container-lowest': '#000000',
        'landing-tertiary-dim': '#f271b5',
        'landing-on-primary': '#00374d',
        'landing-inverse-primary': '#00668b',
        'landing-primary-fixed-dim': '#05a9e3',
        'landing-primary': '#3bbffa',
        'landing-surface-bright': '#1f2b49',
        'landing-surface-tint': '#3bbffa',
        'landing-outline': '#6d758c',
        'landing-on-secondary-fixed': '#192490',
        'landing-surface-container': '#0f1930',
        'landing-error-container': '#9f0519',
        'landing-error': '#ff716c',
        'landing-on-primary-fixed': '#00121d',
        'landing-on-tertiary-fixed-variant': '#73004b',
        'landing-surface-container-high': '#141f38',
        'landing-primary-container': '#22b1ec',
        'landing-on-primary-container': '#002b3d',
        'landing-secondary-container': '#2f3aa3',
        'landing-surface-container-highest': '#192540',
        'landing-on-tertiary-fixed': '#360021',
        'landing-outline-variant': '#40485d',
        'landing-inverse-on-surface': '#4d556b',
        'landing-tertiary-container': '#f673b7',
        'landing-surface': '#060e20',
        'landing-on-primary-fixed-variant': '#003a50',
        'landing-primary-fixed': '#2db7f2',
        'landing-tertiary-fixed-dim': '#f976ba',
        'landing-background': '#060e20',
        'landing-on-background': '#dee5ff',
        'landing-on-secondary-fixed-variant': '#3a45ad',
        'landing-on-secondary': '#000974',
        'landing-secondary-dim': '#8a95ff',
        'landing-on-surface': '#dee5ff',
        'landing-secondary-fixed-dim': '#babfff',
        'landing-on-tertiary': '#5f003e',
        'landing-tertiary-fixed': '#ff8bc5',
        'landing-error-dim': '#d7383b',
        'landing-on-error-container': '#ffa8a3',
        'landing-on-secondary-container': '#c9cdff',
        'landing-on-error': '#490006',
        'landing-on-surface-variant': '#a3aac4',
        'landing-on-tertiary-container': '#4a002f',
        'landing-secondary': '#8a95ff',
        'landing-tertiary': '#ff86c3',
        'landing-inverse-surface': '#faf8ff',
        'landing-surface-container-low': '#091328',

        // ── Modern Dark Cinema design tokens ───────────────────
        'bg-deep':     '#020203',
        'bg-base':     '#050506',
        'bg-elevated': '#0a0a0c',
        'surface':     'rgba(255,255,255,0.05)',
        'surface-hi':  'rgba(255,255,255,0.08)',
        'fg':          '#EDEDEF',
        'fg-muted':    '#8A8F98',
        'fg-subtle':   '#4B5060',
        'accent':      '#5E6AD2',
        'accent-glow': 'rgba(94,106,210,0.2)',
        'accent-hi':   '#7B87E8',
        'border':      'rgba(255,255,255,0.08)',
        'border-hi':   'rgba(255,255,255,0.15)',

        // ── Semantic status ─────────────────────────────────────
        'status-success': '#4ADE80',
        'status-warning': '#FBBF24',
        'status-danger':  '#F87171',
        'status-info':    '#60A5FA',

        // ── Legacy compat (keep existing components working) ────
        'primary':                   '#5E6AD2',
        'secondary':                 '#8B7CF7',
        'background':                '#020203',
        'on-background':             '#EDEDEF',
        'on-surface':                '#EDEDEF',
        'on-surface-variant':        '#8A8F98',
        'surface-container':         '#0a0a0c',
        'surface-container-high':    '#0f1016',
        'surface-container-highest': '#141520',
        'surface-container-low':     '#050506',
        'outline':                   '#4B5060',
        'outline-variant':           'rgba(255,255,255,0.08)',
        'error':                     '#F87171',
        'surface-dim':               '#020203',
        'surface-bright':            '#0f1016',
        'surface-variant':           '#0a0a0c',
        'surface-tint':              '#5E6AD2',
        'on-primary':                '#fff',
        'on-secondary':              '#fff',
        'on-tertiary':               '#fff',
        'tertiary':                  '#F09580',
        'tertiary-dim':              '#F09580',
        'tertiary-fixed':            '#F09580',
        'tertiary-fixed-dim':        '#F09580',
        'on-tertiary-fixed':         '#fff',
        'on-tertiary-fixed-variant': '#fff',
        'on-tertiary-container':     '#fff',
        'tertiary-container':        '#F09580',
        'secondary-dim':             '#8B7CF7',
        'secondary-fixed':           '#8B7CF7',
        'secondary-fixed-dim':       '#8B7CF7',
        'secondary-container':       'rgba(139,124,247,0.15)',
        'on-secondary-fixed':        '#fff',
        'on-secondary-fixed-variant':'#fff',
        'on-secondary-container':    '#8B7CF7',
        'primary-dim':               '#5E6AD2',
        'primary-fixed':             '#5E6AD2',
        'primary-fixed-dim':         '#5E6AD2',
        'primary-container':         'rgba(94,106,210,0.15)',
        'on-primary-fixed':          '#fff',
        'on-primary-fixed-variant':  '#fff',
        'on-primary-container':      '#5E6AD2',
        'inverse-primary':           '#5E6AD2',
        'inverse-surface':           '#EDEDEF',
        'inverse-on-surface':        '#020203',
        'error-container':           'rgba(248,113,113,0.15)',
        'on-error':                  '#fff',
        'on-error-container':        '#F87171',
        'surface-container-lowest':  '#000000',
      },

      fontFamily: {
        sans:     ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['Inter', 'system-ui', 'sans-serif'],
        mono:     ['JetBrains Mono', 'Fira Code', 'monospace'],
      },

      borderRadius: {
        DEFAULT: '10px',
        sm:      '6px',
        md:      '10px',
        lg:      '16px',
        xl:      '20px',
        '2xl':   '24px',
        full:    '9999px',
      },

      boxShadow: {
        pip:      '0 4px 24px rgba(0,0,0,0.5)',
        dropdown: '0 4px 16px rgba(0,0,0,0.4)',
        modal:    '0 16px 48px rgba(0,0,0,0.6)',
        glow:     '0 0 20px rgba(94,106,210,0.3)',
        'glow-sm':'0 0 10px rgba(94,106,210,0.2)',
      },

      transitionTimingFunction: {
        expo: 'cubic-bezier(0.16,1,0.3,1)',
      },

      keyframes: {
        blobDrift: {
          '0%,100%': { transform: 'translate(0,0) scale(1)' },
          '33%':     { transform: 'translate(30px,-20px) scale(1.04)' },
          '66%':     { transform: 'translate(-20px,15px) scale(0.97)' },
        },
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'blob-slow': 'blobDrift 12s ease-in-out infinite',
        'blob-mid':  'blobDrift 16s ease-in-out infinite 4s',
        'fade-up':   'fadeUp 300ms cubic-bezier(0.16,1,0.3,1) both',
        'fade-in':   'fadeIn 200ms ease-out both',
      },
    },
  },
  plugins: [],
}
